### ISSUE TITLE
Can not upload both images for earth and moon

### ISSUE THREAD

**Issue by amplatzer** [Sebwap/M5Dial_moon#1] opened 2024-01-16 07:49 UTC
Hi, after burning the UIFlow 2.0 firmware for M5dial. I have like 1.9MB of space left, how did you upload all images for earth and moon dir?

**Comment by Sebwap** [comment] 2024-01-16 09:03
It's the main problem. I delete almost anything except my program and its pictures, and it's OK.
I was using firmware alpha-28 but it may become difficult with newer version.

**Comment by amplatzer** [comment] 2024-01-16 09:05
> It's the main problem. I delete almost anything except my program and its pictures, and it's OK. I was using firmware alpha-28 but it may become difficult with newer version.

I see, the device does has 8M flash,right? So the UIFlow itself takes almost 6M flash ?

**Comment by amplatzer** [comment] 2024-01-16 09:08
Is there a way to build a Micropython firmware with M5 libraries so I can get rid of UIFlow2?

**Comment by Sebwap** [comment] 2024-01-16 09:09
Maybe, I don't know. The problem is that UIflow include lots of library to manage different sensor from M5Stack.
Another solution is to reprocess pictures to reduce quality, but it's shame I think.

I think UIFlow is open source, so you probably can, but it's far above my level.

**Comment by Sebwap** [comment] 2024-01-16 09:25
I close the issue.
Please see this program as a POC. You are free to generate pictures of whatever, with adapted quality and number to fit the tiny memory capacity of M5Dial :)

**Closed as completed** 2024-01-16 09:26 UTC
